# Generated by Django 2.2.6 on 2019-10-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='content',
            new_name='Roll_Number_and_Names',
        ),
        migrations.RenameField(
            model_name='projectinfo',
            old_name='rollno',
            new_name='description',
        ),
    ]
