# Generated by Django 2.2.6 on 2019-10-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0003_auto_20191008_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='Name_of_Approval_committee_members',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='Observations_or_remarks_by_faculty',
            field=models.TextField(default='No remark given'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='Reccommended',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not given', max_length=20),
        ),
    ]
