# Generated by Django 2.2.6 on 2019-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0004_auto_20191010_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='Reccommended',
            new_name='Recommended',
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='Name_of_Approval_committee_members',
            field=models.TextField(default=''),
        ),
    ]
