# Generated by Django 2.2.6 on 2019-10-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0005_auto_20191010_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='Date_of_Approval',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
