# Generated by Django 2.2 on 2022-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0007_remove_projectinfo_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='Year',
            field=models.CharField(default=2022, max_length=20),
        ),
    ]
